spring:
  # 데이터베이스 연결 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # localhost:3306 뒤의 'javaproject'은 데이터베이스 이름과 일치해야 함.
    url: jdbc:mariadb://localhost:3306/javaproject
    username: root        # 데이터베이스 접속 계정명
    password: ''        # 데이터베이스 접속 비밀번호

  # JPA & Hibernate
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    
    # 하이버네이트 구동 전략 설정
    # update: 엔티티 구조와 DB 테이블 구조를 비교하여 변경된 부분만 자동으로 수정/반영.
    # validate: 엔티티와 테이블이 제대로 매핑되었는지 검증.
    hibernate:
      ddl-auto: none
      
    # 콘솔창에 JPA가 내부적으로 생성해서 날리는 SQL 실행 쿼리문을 출력
    show-sql: true
    
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Thymeleaf (HTML 뷰 템플릿) 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    # 개발 단계에서는 HTML 수정 후 새로고침 시 바로 반영되도록 캐시를 끔
    cache: false

# 전체 애플리케이션 및 JPA 파라미터 로깅 레벨 상세 설정
logging:
  level:
    root: info
    # JPA가 DB에 밀어 넣는 파라미터의 실제 값을 콘솔창에 상세 로그로 찍어주는 옵션
    org.hibernate.orm.results: trace
    org.hibernate.stat: debug